# ========================================================
# Copyright (c) 2026 MGB Not Free Creator
# All Rights Reserved.
#
# Project      : MGB Not Free Music Telegram Bot
# Powered By   : MGB Not Free Creator
# Type         : API Based Telegram Music Bot
#
# Bot          : @MUSIC1_NOT_FREE_BOT
# Channel      : https://t.me/MUSIC_SUPPORT_69
# GitHub       : https://github.com/mgbnotfree-creatur
#
# Unauthorized copying, modification, or redistribut
# of this source code without permission is prohibit
# ========================================================
services:
  - type: worker
    name: MGBNotFreeMusic
    runtime: python
    buildCommand: pip install -U -r requirements.txt
    startCommand: bash start
    plan: free
    
